name: Deploy to Hostinger VPS (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }} << 'EOF'
            cd ~/Protrac/SlnkoFrontend && git checkout main
            git pull origin main
            docker build -t prod_frontend .
            docker stop prod_frontend || true
            docker rm prod_frontend || true
            docker run --name prod_frontend -p 5004:80 -d --env-file .env.prod prod_frontend
          EOF
